# Nixpacks configuration for Coolify deployment
providers = ["node"]

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20.19.0"

[phases.install]
cmds = ["rm -rf package-lock.json node_modules", "npm install --no-audit", "npm rebuild"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
